
document.addEventListener('DOMContentLoaded', function() {
    const familiesElement = document.getElementById('families');
    Object.keys(data).forEach(family => {
        const familyDiv = document.createElement('div');
        familyDiv.className = 'family';
        familyDiv.textContent = family;
        familyDiv.onclick = function() {
            const speciesDiv = this.nextSibling;
            speciesDiv.style.display = speciesDiv.style.display === 'none' ? 'block' : 'none';
        };
        familiesElement.appendChild(familyDiv);

        const speciesList = document.createElement('div');
        speciesList.className = 'species';
        data[family].forEach(species => {
            const speciesItem = document.createElement('div');
            speciesItem.textContent = `${species.name} (${species.latinName})`;
            const imageElement = document.createElement('img');
            imageElement.src = species.imageUrl;
            imageElement.alt = `Image of ${species.name}`;
            imageElement.style.width = '100px'; // Example size, adjust as needed
            speciesItem.appendChild(imageElement);
            speciesList.appendChild(speciesItem);
        });
        familiesElement.appendChild(speciesList);
    });
});

const data = {
    '凤蝶科': [
        { name: '柑橘凤蝶', latinName: 'Papilio xuthus', imageUrl: 'images/Papilio_xuthus.jpg' },
        { name: '碎斑青凤蝶', latinName: 'Graphium chironides', imageUrl: 'images/Graphium_chironides.jpg' },
        { name: '碧凤蝶', latinName: 'Papilio bianor', imageUrl: 'images/Papilio_bianor.jpg' },
        { name: '红珠凤蝶', latinName: 'Pachliopta aristolochiae', imageUrl: 'images/Pachliopta_aristolochiae.jpg' },
        { name: '蓝凤蝶', latinName: 'Papilio protenor', imageUrl: 'images/Papilio_protenor.jpg' },
        { name: '青凤蝶', latinName: 'Graphium sarpedon', imageUrl: 'images/Graphium_sarpedon.jpg' },
    ],
    '列蛾科': [
        { name: '列蛾属待定种', latinName: 'Autosticha sp.', imageUrl: 'images/Autosticha_sp..jpg' },
        { name: '褐带织蛾', latinName: 'Periacma delegata', imageUrl: 'images/Periacma_delegata.jpg' },
    ],
    '刺蛾科': [
        { name: '中国扁刺蛾', latinName: 'Thosea sinensis', imageUrl: 'images/Thosea_sinensis.jpg' },
        { name: '枣奕刺蛾', latinName: 'Phlossa conjuncta', imageUrl: 'images/Phlossa_conjuncta.jpg' },
        { name: '绿刺蛾属待定种', latinName: 'Parasa sp.', imageUrl: 'images/Parasa_sp..jpg' },
        { name: '背刺蛾', latinName: 'Belippa horrida', imageUrl: 'images/Belippa_horrida.jpg' },
        { name: '艳刺蛾', latinName: 'Demonarosa rufotessellata', imageUrl: 'images/Demonarosa_rufotessellata.jpg' },
        { name: '黄刺蛾', latinName: 'Monema flavescens', imageUrl: 'images/Monema_flavescens.jpg' },
        { name: '黑条刺蛾', latinName: 'Striogyia obatera', imageUrl: 'images/Striogyia_obatera.jpg' },
    ],
    '卷蛾科': [
        { name: '圆卷蛾属待定种', latinName: 'Neocalyptis sp.', imageUrl: 'images/Neocalyptis_sp..jpg' },
        { name: '小卷蛾亚科待定种', latinName: 'Olethreutinae gen. sp.', imageUrl: 'images/Olethreutinae_gen._sp..jpg' },
        { name: '旗鱼黄卷蛾', latinName: 'Archips audax', imageUrl: 'images/Archips_audax.jpg' },
        { name: '杨桃小卷蛾', latinName: 'Gatesclarkeana cf. idia', imageUrl: 'images/Gatesclarkeana_cf._idia.jpg' },
        { name: '棉褐带卷蛾', latinName: 'Adoxophyes orana', imageUrl: 'images/Adoxophyes_orana.jpg' },
        { name: '白玫小卷蛾', latinName: 'Notocelia rosaecolana', imageUrl: 'images/Notocelia_rosaecolana.jpg' },
        { name: '白钩小卷蛾', latinName: 'Epiblema foenella', imageUrl: 'images/Epiblema_foenella.jpg' },
        { name: '端小卷蛾属待定种', latinName: 'Phaecasiophora sp.', imageUrl: 'images/Phaecasiophora_sp..jpg' },
        { name: '筒小卷蛾', latinName: 'Rhopalovalva grapholitana', imageUrl: 'images/Rhopalovalva_grapholitana.jpg' },
        { name: '苦楝小卷蛾', latinName: 'Loboschiza koenigiana', imageUrl: 'images/Loboschiza_koenigiana.jpg' },
        { name: '茶小卷叶蛾', latinName: 'Adoxophyes honmai', imageUrl: 'images/Adoxophyes_honmai.jpg' },
        { name: '草小卷蛾属待定种', latinName: 'Celypha sp.', imageUrl: 'images/Celypha_sp..jpg' },
        { name: '镰翅小卷蛾属待定种', latinName: 'Ancylis sp.', imageUrl: 'images/Ancylis_sp..jpg' },
        { name: '黄卷蛾族待定种', latinName: 'Archipini gen. sp.', imageUrl: 'images/Archipini_gen._sp..jpg' },
    ],
    '多翼蛾科': [
        { name: '孔雀多翼蛾', latinName: 'Alucita spilodesma', imageUrl: 'images/Alucita_spilodesma.jpg' },
    ],
    '夜蛾科': [
        { name: '两点尼夜蛾', latinName: 'Anorthoa munda', imageUrl: 'images/Anorthoa_munda.jpg' },
        { name: '丽木冬夜蛾', latinName: 'Xylena formosa', imageUrl: 'images/Xylena_formosa.jpg' },
        { name: '乏夜蛾', latinName: 'Niphonyx segregata', imageUrl: 'images/Niphonyx_segregata.jpg' },
        { name: '兰阳尖翅夜蛾', latinName: 'Belosticta cinerea', imageUrl: 'images/Belosticta_cinerea.jpg' },
        { name: '南方锞纹夜蛾', latinName: 'Chrysodeixis eriosoma', imageUrl: 'images/Chrysodeixis_eriosoma.jpg' },
        { name: '夜蛾科待定种', latinName: 'Noctuidae gen. sp.', imageUrl: 'images/Noctuidae_gen._sp..jpg' },
        { name: '大地老虎', latinName: 'Agrotis tokionis', imageUrl: 'images/Agrotis_tokionis.jpg' },
        { name: '大理石绮夜蛾', latinName: 'Acontia marmoralis', imageUrl: 'images/Acontia_marmoralis.jpg' },
        { name: '委夜蛾属待定种', latinName: 'Athetis sp.', imageUrl: 'images/Athetis_sp..jpg' },
        { name: '实夜蛾属待定种', latinName: 'Heliothis sp.', imageUrl: 'images/Heliothis_sp..jpg' },
        { name: '小地老虎', latinName: 'Agrotis ipsilon', imageUrl: 'images/Agrotis_ipsilon.jpg' },
        { name: '尖遥冬夜蛾', latinName: 'Telorta acuminata', imageUrl: 'images/Telorta_acuminata.jpg' },
        { name: '弱夜蛾', latinName: 'Ozarba punctigera', imageUrl: 'images/Ozarba_punctigera.jpg' },
        { name: '弱夜蛾属待定种', latinName: 'Ozarba sp.', imageUrl: 'images/Ozarba_sp..jpg' },
        { name: '斜纹夜蛾', latinName: 'Spodoptera litura', imageUrl: 'images/Spodoptera_litura.jpg' },
        { name: '易点夜蛾', latinName: 'Condica illecta', imageUrl: 'images/Condica_illecta.jpg' },
        { name: '星卫翅夜蛾', latinName: 'Amyna stellata', imageUrl: 'images/Amyna_stellata.jpg' },
        { name: '曲遥冬夜蛾', latinName: 'Telorta divergens', imageUrl: 'images/Telorta_divergens.jpg' },
        { name: '朽木夜蛾', latinName: 'Axylia putris', imageUrl: 'images/Axylia_putris.jpg' },
        { name: '梨剑纹夜蛾', latinName: 'Acronicta rumicis', imageUrl: 'images/Acronicta_rumicis.jpg' },
        { name: '棉铃夜蛾', latinName: 'Helicoverpa armigera', imageUrl: 'images/Helicoverpa_armigera.jpg' },
        { name: '润鲁夜蛾', latinName: 'Xestia dilatata', imageUrl: 'images/Xestia_dilatata.jpg' },
        { name: '淡剑灰翅夜蛾', latinName: 'Spodoptera depravata', imageUrl: 'images/Spodoptera_depravata.jpg' },
        { name: '灰歹夜蛾', latinName: 'Diarsia canescens', imageUrl: 'images/Diarsia_canescens.jpg' },
        { name: '犁纹黄夜蛾', latinName: 'Xanthodes transversa', imageUrl: 'images/Xanthodes_transversa.jpg' },
        { name: '甜菜夜蛾', latinName: 'Spodoptera exigua', imageUrl: 'images/Spodoptera_exigua.jpg' },
        { name: '番秘夜蛾', latinName: 'Mythimna bani', imageUrl: 'images/Mythimna_bani.jpg' },
        { name: '白斑烦夜蛾', latinName: 'Aedia leucomelas', imageUrl: 'images/Aedia_leucomelas.jpg' },
        { name: '白条银纹夜蛾', latinName: 'Ctenoplusia albostriata', imageUrl: 'images/Ctenoplusia_albostriata.jpg' },
        { name: '白点粘夜蛾', latinName: 'Leucania loreyi', imageUrl: 'images/Leucania_loreyi.jpg' },
        { name: '白纹点夜蛾', latinName: 'Condica albigutta', imageUrl: 'images/Condica_albigutta.jpg' },
        { name: '竹笋禾夜蛾', latinName: 'Bambusiphila vulgaris', imageUrl: 'images/Bambusiphila_vulgaris.jpg' },
        { name: '紫黑扁身夜蛾', latinName: 'Amphipyra livida', imageUrl: 'images/Amphipyra_livida.jpg' },
        { name: '红棕锦葵裳蛾', latinName: 'Rusicada privata', imageUrl: 'images/Rusicada_privata.jpg' },
        { name: '纯肖金夜蛾', latinName: 'Plusiodonta casta', imageUrl: 'images/Plusiodonta_casta.jpg' },
        { name: '苎麻夜蛾', latinName: 'Arcte coerula', imageUrl: 'images/Arcte_coerula.jpg' },
        { name: '豪虎蛾', latinName: 'Scrobigera amatrix', imageUrl: 'images/Scrobigera_amatrix.jpg' },
        { name: '道纹夜蛾', latinName: 'Thysanoplusia daubei', imageUrl: 'images/Thysanoplusia_daubei.jpg' },
        { name: '银纹夜蛾', latinName: 'Argyrogramma agnata', imageUrl: 'images/Argyrogramma_agnata.jpg' },
        { name: '顿秘夜蛾', latinName: 'Mythimna stolida', imageUrl: 'images/Mythimna_stolida.jpg' },
    ],
    '大蚕蛾科': [
        { name: '绿尾大蚕蛾', latinName: 'Actias ningpoana', imageUrl: 'images/Actias_ningpoana.jpg' },
    ],
    '天蛾科': [
        { name: '丁香天蛾', latinName: 'Psilogramma increta', imageUrl: 'images/Psilogramma_increta.jpg' },
        { name: '喜马锤天蛾', latinName: 'Neogurelca himachala', imageUrl: 'images/Neogurelca_himachala.jpg' },
        { name: '构月天蛾', latinName: 'Parum colligata', imageUrl: 'images/Parum_colligata.jpg' },
        { name: '枫天蛾', latinName: 'Cypoides chinensis', imageUrl: 'images/Cypoides_chinensis.jpg' },
        { name: '榆绿天蛾', latinName: 'Callambulyx tatarinovii', imageUrl: 'images/Callambulyx_tatarinovii.jpg' },
        { name: '甘薯天蛾', latinName: 'Agrius convolvuli', imageUrl: 'images/Agrius_convolvuli.jpg' },
        { name: '紫光盾天蛾', latinName: 'Phyllosphingia dissimilis sinensis', imageUrl: 'images/Phyllosphingia_dissimilis_sinensis.jpg' },
        { name: '芋双线天蛾', latinName: 'Theretra oldenlandiae', imageUrl: 'images/Theretra_oldenlandiae.jpg' },
        { name: '西藏斜纹天蛾', latinName: 'Theretra tibetiana', imageUrl: 'images/Theretra_tibetiana.jpg' },
        { name: '豆天蛾', latinName: 'Clanis bilineata', imageUrl: 'images/Clanis_bilineata.jpg' },
        { name: '雀纹天蛾', latinName: 'Theretra japonica', imageUrl: 'images/Theretra_japonica.jpg' },
    ],
    '宽蛾科': [
        { name: '苹凹宽蛾', latinName: 'Acria ceramitis', imageUrl: 'images/Acria_ceramitis.jpg' },
    ],
    '寄蛾科': [
        { name: '名和蝉寄蛾', latinName: 'Epipomponia cf. nawai', imageUrl: 'images/Epipomponia_cf._nawai.jpg' },
    ],
    '尖蛾科': [
        { name: '尖蛾属待定种', latinName: 'Cosmopterix sp.', imageUrl: 'images/Cosmopterix_sp..jpg' },
        { name: '尖蛾科待定种', latinName: 'Cosmopterigidae gen. sp.', imageUrl: 'images/Cosmopterigidae_gen._sp..jpg' },
        { name: '橙红离尖蛾', latinName: 'Labdia semicoccinea', imageUrl: 'images/Labdia_semicoccinea.jpg' },
        { name: '蛾*', latinName: 'Anatrachyntis sp.', imageUrl: 'images/Anatrachyntis_sp..jpg' },
        { name: '黑白离尖蛾', latinName: 'Labdia niphosticta', imageUrl: 'images/Labdia_niphosticta.jpg' },
    ],
    '尺蛾科': [
        { name: '一枝黄花球果尺蛾', latinName: 'Eupithecia virgaureata', imageUrl: 'images/Eupithecia_virgaureata.jpg' },
        { name: '三角璃尺蛾', latinName: 'Krananda latimarginaria', imageUrl: 'images/Krananda_latimarginaria.jpg' },
        { name: '丝棉木金星尺蛾', latinName: 'Abraxas suspecta', imageUrl: 'images/Abraxas_suspecta.jpg' },
        { name: '佳眼尺蛾', latinName: 'Problepsis eucircota', imageUrl: 'images/Problepsis_eucircota.jpg' },
        { name: '刺槐外斑尺蛾', latinName: 'Ectropis excellens', imageUrl: 'images/Ectropis_excellens.jpg' },
        { name: '及角子尺蛾属待定种', latinName: 'Planociampa sp.', imageUrl: 'images/Planociampa_sp..jpg' },
        { name: '双珠严尺蛾', latinName: 'Pylargosceles steganioides', imageUrl: 'images/Pylargosceles_steganioides.jpg' },
        { name: '史氏褐线尺蛾', latinName: 'Timandra stueningi', imageUrl: 'images/Timandra_stueningi.jpg' },
        { name: '合欢庶尺蛾', latinName: 'Chiasmia defixaria', imageUrl: 'images/Chiasmia_defixaria.jpg' },
        { name: '小四点波姬尺蛾', latinName: 'Idaea trisetata', imageUrl: 'images/Idaea_trisetata.jpg' },
        { name: '小用克尺蛾', latinName: 'Jankowskia fuscaria', imageUrl: 'images/Jankowskia_fuscaria.jpg' },
        { name: '小蜻蜓尺蛾', latinName: 'Cystidia couaggaria', imageUrl: 'images/Cystidia_couaggaria.jpg' },
        { name: '尘尺蛾', latinName: 'Hypomecis punctinalis', imageUrl: 'images/Hypomecis_punctinalis.jpg' },
        { name: '尺蛾科待定种', latinName: 'Geometridae gen. sp.', imageUrl: 'images/Geometridae_gen._sp..jpg' },
        { name: '岩尺蛾属待定种', latinName: 'Scopula sp.', imageUrl: 'images/Scopula_sp..jpg' },
        { name: '忍冬尺蛾', latinName: 'Somatina indicataria', imageUrl: 'images/Somatina_indicataria.jpg' },
        { name: '截角尺蛾属待定种', latinName: 'Xerodes sp.', imageUrl: 'images/Xerodes_sp..jpg' },
        { name: '掌尺蛾属待定种', latinName: 'Amraica sp.', imageUrl: 'images/Amraica_sp..jpg' },
        { name: '日本球果尺蛾', latinName: 'Eupithecia subtacincta', imageUrl: 'images/Eupithecia_subtacincta.jpg' },
        { name: '星缘锈腰尺蛾', latinName: 'Hemithea tritonaria', imageUrl: 'images/Hemithea_tritonaria.jpg' },
        { name: '木尺蛾', latinName: 'Xyloscia subspersata', imageUrl: 'images/Xyloscia_subspersata.jpg' },
        { name: '木橑尺蛾', latinName: 'Biston panterinaria', imageUrl: 'images/Biston_panterinaria.jpg' },
        { name: '查冥尺蛾', latinName: 'Heterarmia charon', imageUrl: 'images/Heterarmia_charon.jpg' },
        { name: '核桃四星尺蛾', latinName: 'Ophthalmitis albosignaria', imageUrl: 'images/Ophthalmitis_albosignaria.jpg' },
        { name: '格庶尺蛾', latinName: 'Chiasmia hebesata', imageUrl: 'images/Chiasmia_hebesata.jpg' },
        { name: '桑尺蛾', latinName: 'Phthonandria atrilineata', imageUrl: 'images/Phthonandria_atrilineata.jpg' },
        { name: '桑褶翅尺蛾', latinName: 'Zamacra cf. excavata', imageUrl: 'images/Zamacra_cf._excavata.jpg' },
        { name: '槐庶尺蛾', latinName: 'Semiothisa cinerearia', imageUrl: 'images/Semiothisa_cinerearia.jpg' },
        { name: '毛穿孔尺蛾', latinName: 'Corymica arnearia', imageUrl: 'images/Corymica_arnearia.jpg' },
        { name: '泛尺蛾', latinName: 'Orthonama obstipata', imageUrl: 'images/Orthonama_obstipata.jpg' },
        { name: '泛尺蛾属待定种', latinName: 'Orthonama sp.', imageUrl: 'images/Orthonama_sp..jpg' },
        { name: '泼墨尺蛾', latinName: 'Ninodes splendens', imageUrl: 'images/Ninodes_splendens.jpg' },
        { name: '海绿尺蛾', latinName: 'Pelagodes antiquadraria', imageUrl: 'images/Pelagodes_antiquadraria.jpg' },
        { name: '灰尺蛾属待定种', latinName: 'Plesiomorpha sp.', imageUrl: 'images/Plesiomorpha_sp..jpg' },
        { name: '灰绿片尺蛾', latinName: 'Fascellina plagiata', imageUrl: 'images/Fascellina_plagiata.jpg' },
        { name: '球果尺蛾族待定种', latinName: 'Eupitheciini gen. sp.', imageUrl: 'images/Eupitheciini_gen._sp..jpg' },
        { name: '瑞霜尺蛾', latinName: 'Cleora repulsaria', imageUrl: 'images/Cleora_repulsaria.jpg' },
        { name: '界尺蛾属待定种', latinName: 'Horisme sp.', imageUrl: 'images/Horisme_sp..jpg' },
        { name: '紫带姬尺蛾', latinName: 'Idaea impexa', imageUrl: 'images/Idaea_impexa.jpg' },
        { name: '肾纹绿尺蛾', latinName: 'Comibaena procumbaria', imageUrl: 'images/Comibaena_procumbaria.jpg' },
        { name: '褐徽球果尺蛾', latinName: 'Eupithecia insignioides', imageUrl: 'images/Eupithecia_insignioides.jpg' },
        { name: '钩翅尺蛾', latinName: 'Hyposidra aquilaria', imageUrl: 'images/Hyposidra_aquilaria.jpg' },
        { name: '雪尾尺蛾', latinName: 'Ourapteryx nivea', imageUrl: 'images/Ourapteryx_nivea.jpg' },
        { name: 'nan', latinName: 'Baptini gen. sp.', imageUrl: 'images/Baptini_gen._sp..jpg' },
    ],
    '尾夜蛾科': [
        { name: '鹿尾夜蛾', latinName: 'Eutelia adulatricoides', imageUrl: 'images/Eutelia_adulatricoides.jpg' },
    ],
    '展足蛾科': [
        { name: '桃展足蛾', latinName: 'Stathmopoda auriferella', imageUrl: 'images/Stathmopoda_auriferella.jpg' },
    ],
    '弄蝶科': [
        { name: '直纹稻弄蝶', latinName: 'Parnara guttata', imageUrl: 'images/Parnara_guttata.jpg' },
        { name: '隐纹谷弄蝶', latinName: 'Pelopidas mathias', imageUrl: 'images/Pelopidas_mathias.jpg' },
    ],
    '斑蛾科': [
        { name: '叶斑蛾属待定种', latinName: 'Illiberis sp.', imageUrl: 'images/Illiberis_sp..jpg' },
        { name: '大叶黄杨斑蛾', latinName: 'Pryeria sinica', imageUrl: 'images/Pryeria_sinica.jpg' },
        { name: '网锦斑蛾', latinName: 'Trypanophora semihyalina', imageUrl: 'images/Trypanophora_semihyalina.jpg' },
        { name: '重阳木锦斑蛾', latinName: 'Histia rhodope', imageUrl: 'images/Histia_rhodope.jpg' },
    ],
    '灰蝶科': [
        { name: '亮灰蝶', latinName: 'Lampides boeticus', imageUrl: 'images/Lampides_boeticus.jpg' },
        { name: '尖翅银灰蝶', latinName: 'Curetis acuta', imageUrl: 'images/Curetis_acuta.jpg' },
        { name: '琉璃灰蝶', latinName: 'Celastrina argiolus', imageUrl: 'images/Celastrina_argiolus.jpg' },
        { name: '蓝灰蝶', latinName: 'Cupido argiades', imageUrl: 'images/Cupido_argiades.jpg' },
        { name: '蚜灰蝶', latinName: 'Taraka hamada', imageUrl: 'images/Taraka_hamada.jpg' },
        { name: '酢浆灰蝶', latinName: 'Pseudozizeeria maha', imageUrl: 'images/Pseudozizeeria_maha.jpg' },
        { name: '雅灰蝶', latinName: 'Jamides bochus', imageUrl: 'images/Jamides_bochus.jpg' },
    ],
    '燕蛾科': [
        { name: '斜线燕蛾', latinName: 'Acropteris iphiata', imageUrl: 'images/Acropteris_iphiata.jpg' },
        { name: '蛾*', latinName: 'Oroplema sp.', imageUrl: 'images/Oroplema_sp..jpg' },
    ],
    '瘤蛾科': [
        { name: '旋皮夜蛾', latinName: 'Eligma narcissus', imageUrl: 'images/Eligma_narcissus.jpg' },
        { name: '暗影饰皮瘤蛾', latinName: 'Garella ruficirra', imageUrl: 'images/Garella_ruficirra.jpg' },
        { name: '柿癣皮瘤蛾', latinName: 'Blenina senex', imageUrl: 'images/Blenina_senex.jpg' },
        { name: '癞皮瘤蛾', latinName: 'Gadirtha impingens', imageUrl: 'images/Gadirtha_impingens.jpg' },
        { name: '粉缘钴夜蛾', latinName: 'Earias pudicana', imageUrl: 'images/Earias_pudicana.jpg' },
        { name: '银斑砌石夜蛾', latinName: 'Gabala argentata', imageUrl: 'images/Gabala_argentata.jpg' },
        { name: '锡兰瘤蛾', latinName: 'Nola ceylonica', imageUrl: 'images/Nola_ceylonica.jpg' },
    ],
    '祝蛾科': [
        { name: '米仓织蛾', latinName: 'Martyringa xeraula', imageUrl: 'images/Martyringa_xeraula.jpg' },
        { name: '胡麻绢祝蛾', latinName: 'Scythropiodes leucostola', imageUrl: 'images/Scythropiodes_leucostola.jpg' },
    ],
    '箩纹蛾科': [
        { name: '紫光箩纹蛾', latinName: 'Brahmaea porphyria', imageUrl: 'images/Brahmaea_porphyria.jpg' },
    ],
    '粉蝶科': [
        { name: '东亚豆粉蝶', latinName: 'Colias poliographus', imageUrl: 'images/Colias_poliographus.jpg' },
        { name: '东方菜粉蝶', latinName: 'Pieris canidia', imageUrl: 'images/Pieris_canidia.jpg' },
        { name: '北黄粉蝶', latinName: 'Eurema mandarinula', imageUrl: 'images/Eurema_mandarinula.jpg' },
        { name: '华东黑纹粉蝶', latinName: 'Pieris latouchei', imageUrl: 'images/Pieris_latouchei.jpg' },
        { name: '菜粉蝶', latinName: 'Pieris rapae', imageUrl: 'images/Pieris_rapae.jpg' },
        { name: '黄尖襟粉蝶', latinName: 'Anthocharis scolymus', imageUrl: 'images/Anthocharis_scolymus.jpg' },
    ],
    '细蛾科': [
        { name: '小潜细蛾属待定种', latinName: 'Phyllonorycter sp.', imageUrl: 'images/Phyllonorycter_sp..jpg' },
    ],
    '网蛾科': [
        { name: '栗斜线网蛾', latinName: 'Striglina cancellata', imageUrl: 'images/Striglina_cancellata.jpg' },
    ],
    '罗蛾科': [
        { name: '合欢罗蛾', latinName: 'Homadaula anisocentra', imageUrl: 'images/Homadaula_anisocentra.jpg' },
    ],
    '羽蛾科': [
        { name: '秀羽蛾属待定种', latinName: 'Stenoptilodes sp.', imageUrl: 'images/Stenoptilodes_sp..jpg' },
    ],
    '舞蛾科': [
        { name: '云纹桑舞蛾', latinName: 'Choreutis hyligenes', imageUrl: 'images/Choreutis_hyligenes.jpg' },
    ],
    '舟蛾科': [
        { name: '扇舟蛾属待定种', latinName: 'Clostera sp.', imageUrl: 'images/Clostera_sp..jpg' },
        { name: '杨小舟蛾', latinName: 'Micromelalopha sieversi', imageUrl: 'images/Micromelalopha_sieversi.jpg' },
        { name: '羽齿舟蛾属待定种', latinName: 'Ptilodon sp.', imageUrl: 'images/Ptilodon_sp..jpg' },
    ],
    '草螟科': [
        { name: '井上氏微禾草螟', latinName: 'Microchilo inouei', imageUrl: 'images/Microchilo_inouei.jpg' },
        { name: '亚洲玉米螟', latinName: 'Ostrinia furnacalis', imageUrl: 'images/Ostrinia_furnacalis.jpg' },
        { name: '卡氏果蛀野螟', latinName: 'Thliptoceras cf. caradjai', imageUrl: 'images/Thliptoceras_cf._caradjai.jpg' },
        { name: '台湾卷叶野螟', latinName: 'Syllepte taiwanalis', imageUrl: 'images/Syllepte_taiwanalis.jpg' },
        { name: '叶展须野螟', latinName: 'Eurrhyparodes bracteolalis', imageUrl: 'images/Eurrhyparodes_bracteolalis.jpg' },
        { name: '吉安氏簑水螟', latinName: 'Nymphicula yoshiyasui', imageUrl: 'images/Nymphicula_yoshiyasui.jpg' },
        { name: '大白纹野螟', latinName: 'Chabula telphusalis', imageUrl: 'images/Chabula_telphusalis.jpg' },
        { name: '小筒水螟', latinName: 'Parapoynx diminutalis', imageUrl: 'images/Parapoynx_diminutalis.jpg' },
        { name: '小蜡绢须野螟', latinName: 'Palpita inusitata', imageUrl: 'images/Palpita_inusitata.jpg' },
        { name: '微草螟属待定种', latinName: 'Glaucocharis sp.', imageUrl: 'images/Glaucocharis_sp..jpg' },
        { name: '斑野螟亚科待定种', latinName: 'Spilomelinae gen. sp.', imageUrl: 'images/Spilomelinae_gen._sp..jpg' },
        { name: '早熟禾拟茎草螟', latinName: 'Parapediasia teterrella', imageUrl: 'images/Parapediasia_teterrella.jpg' },
        { name: '枇杷卷叶野螟', latinName: 'Patania balteata', imageUrl: 'images/Patania_balteata.jpg' },
        { name: '水稻切叶野螟', latinName: 'Herpetogramma licarsisalis', imageUrl: 'images/Herpetogramma_licarsisalis.jpg' },
        { name: '泡桐卷野螟', latinName: 'Pycnarmon cribrata', imageUrl: 'images/Pycnarmon_cribrata.jpg' },
        { name: '瓜绢野螟', latinName: 'Diaphania indica', imageUrl: 'images/Diaphania_indica.jpg' },
        { name: '甜菜白带野螟', latinName: 'Spoladea recurvalis', imageUrl: 'images/Spoladea_recurvalis.jpg' },
        { name: '白斑翅野螟', latinName: 'Bocchoris inspersalis', imageUrl: 'images/Bocchoris_inspersalis.jpg' },
        { name: '白蜡绢须野螟', latinName: 'Palpita nigropunctalis', imageUrl: 'images/Palpita_nigropunctalis.jpg' },
        { name: '稻纵卷叶螟', latinName: 'Cnaphalocrocis medinalis', imageUrl: 'images/Cnaphalocrocis_medinalis.jpg' },
        { name: '苔螟亚科待定种', latinName: 'Scopariinae gen. sp.', imageUrl: 'images/Scopariinae_gen._sp..jpg' },
        { name: '菜螟', latinName: 'Hellula undalis', imageUrl: 'images/Hellula_undalis.jpg' },
        { name: '葡萄切叶野螟', latinName: 'Herpetogramma luctuosalis', imageUrl: 'images/Herpetogramma_luctuosalis.jpg' },
        { name: '蛾*', latinName: 'Dolicharthria bruguieralis', imageUrl: 'images/Dolicharthria_bruguieralis.jpg' },
        { name: '蛾*', latinName: 'Sericoplaga sp.', imageUrl: 'images/Sericoplaga_sp..jpg' },
        { name: '褐线新蕨螟', latinName: 'Neomusotima fuscolinealis', imageUrl: 'images/Neomusotima_fuscolinealis.jpg' },
        { name: '褐翅切叶野螟', latinName: 'Herpetogramma rudis', imageUrl: 'images/Herpetogramma_rudis.jpg' },
        { name: '褐萍水螟', latinName: 'Elophila turbata', imageUrl: 'images/Elophila_turbata.jpg' },
        { name: '豆野螟', latinName: 'Maruca vitrata', imageUrl: 'images/Maruca_vitrata.jpg' },
        { name: '长须曲角野螟', latinName: 'Camptomastix hisbonalis', imageUrl: 'images/Camptomastix_hisbonalis.jpg' },
        { name: '黄杨绢野螟', latinName: 'Cydalima perspectalis', imageUrl: 'images/Cydalima_perspectalis.jpg' },
        { name: '黄环蚀叶野螟', latinName: 'Lamprosema tampiusalis', imageUrl: 'images/Lamprosema_tampiusalis.jpg' },
        { name: '黄翅缀叶野螟', latinName: 'Botyodes diniasalis', imageUrl: 'images/Botyodes_diniasalis.jpg' },
        { name: '黑点蚀叶野螟', latinName: 'Lamprosema commixta', imageUrl: 'images/Lamprosema_commixta.jpg' },
        { name: '齿斑绢丝野螟', latinName: 'Glyphodes onychinalis', imageUrl: 'images/Glyphodes_onychinalis.jpg' },
    ],
    '蓑蛾科': [
        { name: '蓑蛾科待定种', latinName: 'Psychidae gen. sp.', imageUrl: 'images/Psychidae_gen._sp..jpg' },
    ],
    '蚕蛾科': [
        { name: '桑蟥', latinName: 'Rondotia menciana', imageUrl: 'images/Rondotia_menciana.jpg' },
        { name: '白弧野蚕蛾', latinName: 'Bombyx lemeepauli', imageUrl: 'images/Bombyx_lemeepauli.jpg' },
        { name: '野蚕蛾', latinName: 'Bombyx mandarina', imageUrl: 'images/Bombyx_mandarina.jpg' },
    ],
    '蛱蝶科': [
        { name: '娑环蛱蝶', latinName: 'Neptis soma', imageUrl: 'images/Neptis_soma.jpg' },
        { name: '密纹矍眼蝶', latinName: 'Ypthima multistriata', imageUrl: 'images/Ypthima_multistriata.jpg' },
        { name: '小环蛱蝶', latinName: 'Neptis sappho', imageUrl: 'images/Neptis_sappho.jpg' },
        { name: '小红蛱蝶', latinName: 'Vanessa cardui', imageUrl: 'images/Vanessa_cardui.jpg' },
        { name: '拟斑脉蛱蝶', latinName: 'Hestina persimilis', imageUrl: 'images/Hestina_persimilis.jpg' },
        { name: '斐豹蛱蝶', latinName: 'Argyreus hyperbius', imageUrl: 'images/Argyreus_hyperbius.jpg' },
        { name: '柳紫闪蛱蝶', latinName: 'Apatura ilia', imageUrl: 'images/Apatura_ilia.jpg' },
        { name: '猫蛱蝶', latinName: 'Timelaea maculata', imageUrl: 'images/Timelaea_maculata.jpg' },
        { name: '琉璃蛱蝶', latinName: 'Kaniska canace', imageUrl: 'images/Kaniska_canace.jpg' },
        { name: '白带螯蛱蝶', latinName: 'Charaxes bernardus', imageUrl: 'images/Charaxes_bernardus.jpg' },
        { name: '阿矍眼蝶', latinName: 'Ypthima argus', imageUrl: 'images/Ypthima_argus.jpg' },
        { name: '黄钩蛱蝶', latinName: 'Polygonia c-aureum', imageUrl: 'images/Polygonia_c-aureum.jpg' },
    ],
    '螟蛾科': [
        { name: '丛螟亚科待定种', latinName: 'Epipaschiinae gen. sp.', imageUrl: 'images/Epipaschiinae_gen._sp..jpg' },
        { name: '并脉岐角螟', latinName: 'Endotricha theonalis', imageUrl: 'images/Endotricha_theonalis.jpg' },
        { name: '斑粉螟', latinName: 'Pyralis pictalis', imageUrl: 'images/Pyralis_pictalis.jpg' },
        { name: '柯基纹丛螟', latinName: 'Stericta kogii', imageUrl: 'images/Stericta_kogii.jpg' },
        { name: '梨峰斑螟', latinName: 'Acrobasis pirivorella', imageUrl: 'images/Acrobasis_pirivorella.jpg' },
        { name: '歧角螟属待定种', latinName: 'Endotricha sp.', imageUrl: 'images/Endotricha_sp..jpg' },
        { name: '瘤丛螟属待定种', latinName: 'Orthaga sp.', imageUrl: 'images/Orthaga_sp..jpg' },
        { name: '蛾*', latinName: 'Ptyomaxia swinhoeella', imageUrl: 'images/Ptyomaxia_swinhoeella.jpg' },
        { name: '金黄螟', latinName: 'Pyralis regalis', imageUrl: 'images/Pyralis_regalis.jpg' },
    ],
    '裳蛾科': [
        { name: '三线绮夜蛾', latinName: 'Autoba trilinea', imageUrl: 'images/Autoba_trilinea.jpg' },
        { name: '丹美苔蛾', latinName: 'Miltochrista sanguinea', imageUrl: 'images/Miltochrista_sanguinea.jpg' },
        { name: '人纹污灯蛾', latinName: 'Spilarctia subcarnea', imageUrl: 'images/Spilarctia_subcarnea.jpg' },
        { name: '优雪苔蛾', latinName: 'Cyana hamata hamata', imageUrl: 'images/Cyana_hamata_hamata.jpg' },
        { name: '伟长须夜蛾', latinName: 'Herminia vermiculata', imageUrl: 'images/Herminia_vermiculata.jpg' },
        { name: '冉地苔蛾', latinName: 'Nudaria ranruna', imageUrl: 'images/Nudaria_ranruna.jpg' },
        { name: '冥毒蛾', latinName: 'Lymantria sinica', imageUrl: 'images/Lymantria_sinica.jpg' },
        { name: '南夜蛾属待定种', latinName: 'Ericeia sp.', imageUrl: 'images/Ericeia_sp..jpg' },
        { name: '变色夜蛾', latinName: 'Hypopyra vespertilio', imageUrl: 'images/Hypopyra_vespertilio.jpg' },
        { name: '土苔蛾属待定种', latinName: 'Eilema sp.', imageUrl: 'images/Eilema_sp..jpg' },
        { name: '广鹿蛾', latinName: 'Amata emma', imageUrl: 'images/Amata_emma.jpg' },
        { name: '折带黄毒蛾属待定种', latinName: 'Artaxa sp.', imageUrl: 'images/Artaxa_sp..jpg' },
        { name: '旋目夜蛾', latinName: 'Spirama retorta', imageUrl: 'images/Spirama_retorta.jpg' },
        { name: '曲带双衲夜蛾', latinName: 'Dinumma deponens', imageUrl: 'images/Dinumma_deponens.jpg' },
        { name: '朋闪夜蛾属待定种', latinName: 'Hypersypnoides sp.', imageUrl: 'images/Hypersypnoides_sp..jpg' },
        { name: '朽叶夜蛾属待定种', latinName: 'Bastilla sp.', imageUrl: 'images/Bastilla_sp..jpg' },
        { name: '枯叶夜蛾', latinName: 'Eudocima tyrannus', imageUrl: 'images/Eudocima_tyrannus.jpg' },
        { name: '棕毒蛾属待定种', latinName: 'Ilema sp.', imageUrl: 'images/Ilema_sp..jpg' },
        { name: '楞亥夜蛾', latinName: 'Hydrillodes lentalis', imageUrl: 'images/Hydrillodes_lentalis.jpg' },
        { name: '残夜蛾属待定种', latinName: 'Colobochyla sp.', imageUrl: 'images/Colobochyla_sp..jpg' },
        { name: '毛胫夜蛾', latinName: 'Mocis undata', imageUrl: 'images/Mocis_undata.jpg' },
        { name: '沟翅裳蛾属待定种', latinName: 'Hypospila sp.', imageUrl: 'images/Hypospila_sp..jpg' },
        { name: '浓眉夜蛾', latinName: 'Pangrapta perturbans', imageUrl: 'images/Pangrapta_perturbans.jpg' },
        { name: '涓夜蛾', latinName: 'Rivula leucanioides', imageUrl: 'images/Rivula_leucanioides.jpg' },
        { name: '涓夜蛾', latinName: 'Rivula sericealis', imageUrl: 'images/Rivula_sericealis.jpg' },
        { name: '涡猎夜蛾', latinName: 'Eublemma cochylioides', imageUrl: 'images/Eublemma_cochylioides.jpg' },
        { name: '灰白灯蛾', latinName: 'Creatonotos transiens vacillans', imageUrl: 'images/Creatonotos_transiens_vacillans.jpg' },
        { name: '玫瑰巾夜蛾', latinName: 'Bastilla arctotaenia', imageUrl: 'images/Bastilla_arctotaenia.jpg' },
        { name: '白点巧夜蛾', latinName: 'Oruza albigutta', imageUrl: 'images/Oruza_albigutta.jpg' },
        { name: '石榴巾夜蛾', latinName: 'Dysgonia stuposa', imageUrl: 'images/Dysgonia_stuposa.jpg' },
        { name: '禾髯须夜蛾', latinName: 'Hypena poa', imageUrl: 'images/Hypena_poa.jpg' },
        { name: '窄缘施夜蛾', latinName: 'Schrankia costaestrigalis', imageUrl: 'images/Schrankia_costaestrigalis.jpg' },
        { name: '线丽毒蛾', latinName: 'Calliteara grotei', imageUrl: 'images/Calliteara_grotei.jpg' },
        { name: '绕环夜蛾', latinName: 'Spirama helicina', imageUrl: 'images/Spirama_helicina.jpg' },
        { name: '肘析夜蛾', latinName: 'Sypnoides olena', imageUrl: 'images/Sypnoides_olena.jpg' },
        { name: '蕾鹿蛾', latinName: 'Amata germana', imageUrl: 'images/Amata_germana.jpg' },
        { name: '蚪目夜蛾', latinName: 'Metopta rectifasciata', imageUrl: 'images/Metopta_rectifasciata.jpg' },
        { name: '蛾*', latinName: 'Katha sp.', imageUrl: 'images/Katha_sp..jpg' },
        { name: '蛾*', latinName: 'Hypena obacerralis', imageUrl: 'images/Hypena_obacerralis.jpg' },
        { name: '裳蛾科待定种', latinName: 'Erebidae gen. sp.', imageUrl: 'images/Erebidae_gen._sp..jpg' },
        { name: '赭灰裴夜蛾', latinName: 'Sophta ruficeps', imageUrl: 'images/Sophta_ruficeps.jpg' },
        { name: '赭黄长须夜蛾', latinName: 'Herminia arenosa', imageUrl: 'images/Herminia_arenosa.jpg' },
        { name: '迴猎夜蛾', latinName: 'Eublemma anachoresis', imageUrl: 'images/Eublemma_anachoresis.jpg' },
        { name: '镰须夜蛾属待定种', latinName: 'Zanclognatha sp.', imageUrl: 'images/Zanclognatha_sp..jpg' },
        { name: '长须夜蛾属待定种', latinName: 'Herminia sp.', imageUrl: 'images/Herminia_sp..jpg' },
        { name: '雪灯蛾属待定种', latinName: 'Spilosoma sp.', imageUrl: 'images/Spilosoma_sp..jpg' },
        { name: '青安钮夜蛾', latinName: 'Ophiusa tirhaca', imageUrl: 'images/Ophiusa_tirhaca.jpg' },
        { name: '鞍长须夜蛾', latinName: 'Herminia annulata', imageUrl: 'images/Herminia_annulata.jpg' },
        { name: '魔目夜蛾', latinName: 'Erebus ephesperis', imageUrl: 'images/Erebus_ephesperis.jpg' },
        { name: '鸟嘴壶夜蛾', latinName: 'Oraesia excavata', imageUrl: 'images/Oraesia_excavata.jpg' },
        { name: '黄痣苔蛾', latinName: 'Stigmatophora flava', imageUrl: 'images/Stigmatophora_flava.jpg' },
        { name: '黑点贫夜蛾', latinName: 'Simplicia rectalis', imageUrl: 'images/Simplicia_rectalis.jpg' },
    ],
    '谷蛾科': [
        { name: '谷蛾科待定种', latinName: 'Tineidae gen. sp.', imageUrl: 'images/Tineidae_gen._sp..jpg' },
    ],
    '钩蛾科': [
        { name: '大斑波纹蛾', latinName: 'Thyatira batis formosicola', imageUrl: 'images/Thyatira_batis_formosicola.jpg' },
        { name: '接骨木山钩蛾', latinName: 'Oreta loochooana', imageUrl: 'images/Oreta_loochooana.jpg' },
    ],
    '长角蛾科': [
        { name: '优纹长角蛾', latinName: 'Nemophora optima', imageUrl: 'images/Nemophora_optima.jpg' },
        { name: '黄带长角蛾', latinName: 'Nemophora decisella', imageUrl: 'images/Nemophora_decisella.jpg' },
    ],
    '驼蛾科': [
        { name: '柚木驼蛾', latinName: 'Hyblaea puera', imageUrl: 'images/Hyblaea_puera.jpg' },
    ],
    '麦蛾科': [
        { name: '棕麦蛾属待定种', latinName: 'Dichomeris sp.', imageUrl: 'images/Dichomeris_sp..jpg' },
        { name: '甘薯麦蛾', latinName: 'Brachmia macroscopa', imageUrl: 'images/Brachmia_macroscopa.jpg' },
        { name: '蛾*', latinName: 'Petalostomella sp.', imageUrl: 'images/Petalostomella_sp..jpg' },
        { name: '衣蛾', latinName: 'Tinea pellionella', imageUrl: 'images/Tinea_pellionella.jpg' },
        { name: '角瓣发麦蛾', latinName: 'Faristenia cornutivalvaris', imageUrl: 'images/Faristenia_cornutivalvaris.jpg' },
        { name: '鸡血藤棕麦蛾', latinName: 'Dichomeris oceanis', imageUrl: 'images/Dichomeris_oceanis.jpg' },
    ],
};
